Repository Kernel360/KBE5_HALO_BE, pull requests merged in 2025-07, with the labels that each got.

#232 [Feature] Swagger UI를 DTO에 추가 적용
  admin/src/main/java/com/kernel/admin/domain/entity/Board.java
  admin/src/main/java/com/kernel/admin/domain/enums/BoardType.java
  admin/src/main/java/com/kernel/admin/service/dto/request/AdminSearchReqDTO.java
  admin/src/main/java/com/kernel/admin/service/dto/request/AdminSignupReqDTO.java
  admin/src/main/java/com/kernel/admin/service/dto/response/AdminDetailRspDTO.java
  admin/src/main/java/com/kernel/admin/service/dto/response/AdminRspDTO.java
  admin/src/main/java/com/kernel/admin/service/dto/response/AdminSearchRspDTO.java
  evaluation/src/main/java/com/kernel/evaluation/common/enums/FeedbackType.java
  evaluation/src/main/java/com/kernel/evaluation/common/enums/ReviewAuthorType.java
  evaluation/src/main/java/com/kernel/evaluation/service/feedback/dto/request/CustomerFeedbackReqDTO.java
  evaluation/src/main/java/com/kernel/evaluation/service/feedback/dto/response/CustomerFeedbackRspDTO.java
  evaluation/src/main/java/com/kernel/evaluation/service/feedback/dto/response/CustomerFeedbackUpdateRspDTO.java
  evaluation/src/main/java/com/kernel/evaluation/service/review/dto/request/ManagerReviewSearchCondDTO.java
  evaluation/src/main/java/com/kernel/evaluation/service/review/dto/request/ReviewCreateReqDTO.java
  evaluation/src/main/java/com/kernel/evaluation/service/review/dto/request/ReviewUpdateReqDTO.java
  evaluation/src/main/java/com/kernel/evaluation/service/review/dto/response/CustomerReviewRspDTO.java
  evaluation/src/main/java/com/kernel/evaluation/service/review/dto/response/ManagerReviewPageRspDTO.java
  evaluation/src/main/java/com/kernel/evaluation/service/review/dto/response/ManagerReviewRspDTO.java
  global/src/main/java/com/kernel/global/service/dto/condition/AdminUserSearchCondition.java
  global/src/main/java/com/kernel/global/service/dto/request/FileUpdateReqDTO.java
  global/src/main/java/com/kernel/global/service/dto/request/FileUploadReqDTO.java
  global/src/main/java/com/kernel/global/service/dto/request/PresignedUrlReqDTO.java
  global/src/main/java/com/kernel/global/service/dto/response/ApiResponse.java
  global/src/main/java/com/kernel/global/service/dto/response/ErrorResponse.java
  global/src/main/java/com/kernel/global/service/dto/response/FileGetRspDTO.java
  global/src/main/java/com/kernel/global/service/dto/response/FileUpdateRspDTO.java
  global/src/main/java/com/kernel/global/service/dto/response/FileUploadRspDTO.java
  global/src/main/java/com/kernel/global/service/dto/response/PresignedUrlRspDTO.java
  inquiry/src/main/java/com/kernel/inquiry/service/dto/request/InquiryCreateReqDTO.java
  inquiry/src/main/java/com/kernel/inquiry/service/dto/request/InquirySearchReqDTO.java
  inquiry/src/main/java/com/kernel/inquiry/service/dto/request/InquiryUpdateReqDTO.java
  inquiry/src/main/java/com/kernel/inquiry/service/dto/request/ReplyCreateReqDTO.java
  inquiry/src/main/java/com/kernel/inquiry/service/dto/response/InquiryDetailRspDTO.java
  inquiry/src/main/java/com/kernel/inquiry/service/dto/response/InquirySummaryRspDTO.java
  member/src/main/java/com/kernel/member/service/request/AvailableTimeReqDTO.java
  member/src/main/java/com/kernel/member/service/request/AvailableTimeUpdateReqDTO.java
  member/src/main/java/com/kernel/member/service/request/CustomerReqDTO.java
  member/src/main/java/com/kernel/member/service/request/CustomerSignupReqDTO.java
  member/src/main/java/com/kernel/member/service/request/CustomerUpdateReqDTO.java
  member/src/main/java/com/kernel/member/service/request/ManagerReqDTO.java
  member/src/main/java/com/kernel/member/service/request/ManagerSignupReqDTO.java
  member/src/main/java/com/kernel/member/service/request/ManagerTerminationReqDTO.java
  member/src/main/java/com/kernel/member/service/request/ManagerUpdateInfoReqDTO.java
  member/src/main/java/com/kernel/member/service/request/ManagerUpdateReqDTO.java
  member/src/main/java/com/kernel/member/service/request/UserInfoSignupReqDTO.java
  member/src/main/java/com/kernel/member/service/request/UserSignupReqDTO.java
  member/src/main/java/com/kernel/member/service/response/AvailableTimeRspDTO.java
  member/src/main/java/com/kernel/member/service/response/CustomerDetailRspDTO.java
  member/src/main/java/com/kernel/member/service/response/ManagerDetailRspDTO.java
  reservation/src/main/java/com/kernel/reservation/repository/CustomManagerReservationRepositoryImpl.java
  reservation/src/main/java/com/kernel/reservation/service/request/ManagerReservationSearchCondDTO.java
  reservation/src/main/java/com/kernel/reservation/service/response/ManagerReservationRspDTO.java
  reservation/src/main/java/com/kernel/reservation/service/response/ManagerReservationSummaryRspDTO.java
Labels: 🔨 feature

#238 [refactor] 수요자 회원가입 수정
  member/src/main/java/com/kernel/member/controller/CustomerController.java
  member/src/main/java/com/kernel/member/domain/entity/Customer.java
  member/src/main/java/com/kernel/member/repository/CustomerStatisticRepository.java
  member/src/main/java/com/kernel/member/service/CustomerServiceImpl.java
  member/src/main/java/com/kernel/member/service/request/CustomerSignupReqDTO.java
Labels: 🔧 refactor

#239 [수요자] 예약 기능 개선 및 포인트 결제 기능 구현
  common/src/main/java/com/kernel/common/admin/entity/AccountStatus.java
  common/src/main/java/com/kernel/common/admin/entity/Admin.java
  common/src/main/java/com/kernel/common/manager/entity/AvailableTime.java
  common/src/main/java/com/kernel/common/manager/entity/CleaningLog.java
  common/src/main/java/com/kernel/common/manager/entity/Manager.java
  global/src/main/java/com/kernel/global/common/constant/SecurityUrlConstants.java
  inquiry/src/main/java/com/kernel/inquiry/controller/inquiry/InquiryCustomerController.java
  member/src/main/java/com/kernel/member/controller/CustomerController.java
  member/src/main/java/com/kernel/member/domain/entity/AvailableTime.java
  member/src/main/java/com/kernel/member/domain/entity/Customer.java
  member/src/main/java/com/kernel/member/service/CustomerService.java
  member/src/main/java/com/kernel/member/service/CustomerServiceImpl.java
  payment/src/main/java/com/kernel/payment/domain/Payment.java
  payment/src/main/java/com/kernel/payment/repository/.gitkeep
  payment/src/main/java/com/kernel/payment/repository/PaymentRepository.java
  payment/src/main/java/com/kernel/payment/service/.gitkeep
  payment/src/main/java/com/kernel/payment/service/PaymentService.java
  payment/src/main/java/com/kernel/payment/service/PaymentServiceImpl.java
  payment/src/main/java/com/kernel/payment/service/request/ReservationPayReqDTO.java
  reservation/src/main/java/com/kernel/reservation/common/enums/ReservationErrorCode.java
  reservation/src/main/java/com/kernel/reservation/common/exception/InsufficientPointsException.java
  reservation/src/main/java/com/kernel/reservation/common/handler/ReservationExceptionHandler.java
  reservation/src/main/java/com/kernel/reservation/controller/CustomerReservationController.java
  reservation/src/main/java/com/kernel/reservation/domain/entity/ReservationCancel.java
  reservation/src/main/java/com/kernel/reservation/repository/CustomCustomerReservationRepositoryImpl.java
  reservation/src/main/java/com/kernel/reservation/repository/common/CustomMatchRepositoryImpl.java
  reservation/src/main/java/com/kernel/reservation/service/CustomerReservationService.java
  reservation/src/main/java/com/kernel/reservation/service/CustomerReservationServiceImpl.java
  reservation/src/main/java/com/kernel/reservation/service/ExtraServiceServiceImpl.java
  reservation/src/main/java/com/kernel/reservation/service/MatchService.java
  reservation/src/main/java/com/kernel/reservation/service/MatchServiceImpl.java
  reservation/src/main/java/com/kernel/reservation/service/info/CustomerReservationDetailInfo.java
  reservation/src/main/java/com/kernel/reservation/service/info/CustomerReservationSummaryInfo.java
  reservation/src/main/java/com/kernel/reservation/service/info/ExtraServiceInfo.java
  reservation/src/main/java/com/kernel/reservation/service/info/ReservationCancelInfo.java
  reservation/src/main/java/com/kernel/reservation/service/info/ReviewInfo.java
  reservation/src/main/java/com/kernel/reservation/service/request/ChooseManagerReqDTO.java
  reservation/src/main/java/com/kernel/reservation/service/request/ReservationConfirmReqDTO.java
  reservation/src/main/java/com/kernel/reservation/service/response/CustomerReservationConfirmRspDTO.java
  reservation/src/main/java/com/kernel/reservation/service/response/CustomerReservationDetailRspDTO.java
  reservation/src/main/java/com/kernel/reservation/service/response/common/ReservationErrorResponse.java
  shared-domain/src/main/java/com/kernel/sharedDomain/domain/entity/Reservation.java
Labels: 🔨 feature, 🔧 refactor

#245 [수요자] 예약시 포인트 결제
  global/src/main/java/com/kernel/global/common/enums/ErrorCode.java
  global/src/main/java/com/kernel/global/common/enums/ErrorCodeInterface.java
  global/src/main/java/com/kernel/global/service/dto/response/ErrorResponse.java
  member/src/main/java/com/kernel/member/common/enums/MemberErrorCode.java
  member/src/main/java/com/kernel/member/common/enums/PointChargeType.java
  member/src/main/java/com/kernel/member/common/exception/PointException.java
  member/src/main/java/com/kernel/member/common/handler/MemberExceptionHandler.java
  member/src/main/java/com/kernel/member/controller/CustomerController.java
  member/src/main/java/com/kernel/member/domain/entity/UserInfo.java
  member/src/main/java/com/kernel/member/service/CustomerService.java
  member/src/main/java/com/kernel/member/service/CustomerServiceImpl.java
  member/src/main/java/com/kernel/member/service/request/ChargePointReqDTO.java
  payment/src/main/java/com/kernel/payment/common/enums/PaymentErrorCode.java
  payment/src/main/java/com/kernel/payment/common/enums/PaymentStatus.java
  payment/src/main/java/com/kernel/payment/common/exception/AlreadyPaidException.java
  payment/src/main/java/com/kernel/payment/common/exception/InsufficientPointsException.java
  payment/src/main/java/com/kernel/payment/common/exception/InvalidPaymentAmountException.java
  payment/src/main/java/com/kernel/payment/common/exception/NotFoundPaymentException.java
  payment/src/main/java/com/kernel/payment/common/exception/PaymentCancelNotAllowedException.java
  payment/src/main/java/com/kernel/payment/common/exception/PaymentException.java
  payment/src/main/java/com/kernel/payment/common/handler/PaymentExceptionHandler.java
  payment/src/main/java/com/kernel/payment/domain/Payment.java
  payment/src/main/java/com/kernel/payment/repository/PaymentRepository.java
  payment/src/main/java/com/kernel/payment/service/PaymentService.java
  payment/src/main/java/com/kernel/payment/service/PaymentServiceImpl.java
  reservation/src/main/java/com/kernel/reservation/common/enums/ReservationErrorCode.java
  reservation/src/main/java/com/kernel/reservation/common/exception/NoAvailableManagerException.java
  reservation/src/main/java/com/kernel/reservation/common/handler/ReservationExceptionHandler.java
  reservation/src/main/java/com/kernel/reservation/controller/CustomerReservationController.java
  reservation/src/main/java/com/kernel/reservation/repository/CustomCustomerReservationRepository.java
  reservation/src/main/java/com/kernel/reservation/repository/CustomCustomerReservationRepositoryImpl.java
  reservation/src/main/java/com/kernel/reservation/repository/common/CustomMatchRepositoryImpl.java
  reservation/src/main/java/com/kernel/reservation/service/CustomerReservationService.java
  reservation/src/main/java/com/kernel/reservation/service/CustomerReservationServiceImpl.java
  reservation/src/main/java/com/kernel/reservation/service/MatchServiceImpl.java
  reservation/src/main/java/com/kernel/reservation/service/info/CustomerReservationConfirmInfo.java
  reservation/src/main/java/com/kernel/reservation/service/request/ReservationCancelReqDTO.java
  reservation/src/main/java/com/kernel/reservation/service/response/CustomerReservationConfirmRspDTO.java
Labels: 🔨 feature, 🔧 refactor

#242 [Refactor] 관리자의 수요자 정보 조회 기능 리펙토링
  common/src/main/java/com/kernel/common/admin/controller/AdminAccountController.java
  common/src/main/java/com/kernel/common/admin/controller/AdminCustomerController.java
  common/src/main/java/com/kernel/common/admin/controller/AdminManagerController.java
  common/src/main/java/com/kernel/common/admin/dto/request/AdminManagerSearchReqDTO.java
  common/src/main/java/com/kernel/common/admin/dto/request/AdminSearchReqDTO.java
  common/src/main/java/com/kernel/common/admin/dto/request/AdminSignupReqDTO.java
  common/src/main/java/com/kernel/common/admin/dto/request/AdminUpdateReqDTO.java
  common/src/main/java/com/kernel/common/admin/dto/response/AdminCustomerResDto.java
  common/src/main/java/com/kernel/common/admin/dto/response/AdminManagerRspDTO.java
  common/src/main/java/com/kernel/common/admin/dto/response/AdminManagerSummaryRspDTO.java
  common/src/main/java/com/kernel/common/admin/dto/response/AdminRspDTO.java
  common/src/main/java/com/kernel/common/admin/dto/response/AdminSearchRspDTO.java
  common/src/main/java/com/kernel/common/admin/repository/AdminCustomerRepository.java
  common/src/main/java/com/kernel/common/admin/repository/AdminRepository.java
  common/src/main/java/com/kernel/common/admin/repository/CustomAdminRepository.java
  common/src/main/java/com/kernel/common/admin/repository/CustomAdminRepositoryImpl.java
  common/src/main/java/com/kernel/common/admin/service/AdminCustomerService.java
  common/src/main/java/com/kernel/common/admin/service/AdminCustomerServiceImpl.java
  common/src/main/java/com/kernel/common/admin/service/AdminManagerService.java
  common/src/main/java/com/kernel/common/admin/service/AdminManagerServiceImpl.java
  global/src/main/java/com/kernel/global/common/exception/UserExceptionHandler.java
  global/src/main/java/com/kernel/global/repository/UserRepository.java
  member/src/main/java/com/kernel/member/common/exception/CustomerNotFoundException.java
  member/src/main/java/com/kernel/member/common/exception/MemberExceptionHandler.java
  member/src/main/java/com/kernel/member/controller/AdminCustomerController.java
  member/src/main/java/com/kernel/member/repository/CustomCustomerRepository.java
  member/src/main/java/com/kernel/member/repository/CustomCustomerRepositoryImpl.java
  member/src/main/java/com/kernel/member/repository/CustomerRepository.java
  member/src/main/java/com/kernel/member/service/AdminCustomerService.java
  member/src/main/java/com/kernel/member/service/AdminCustomerServiceImpl.java
  member/src/main/java/com/kernel/member/service/common/info/AdminCustomerSummaryInfo.java
  member/src/main/java/com/kernel/member/service/request/AdminCustomerSearchReqDTO.java
  member/src/main/java/com/kernel/member/service/response/AdminCustomerSummaryRspDTO.java
Labels: 🔧 refactor

#250 [Fix] 같은 이름을 가진 예외 처리 핸들러 삭제
  global/src/main/java/com/kernel/global/common/handler/UserExceptionHandler.java
  member/src/main/java/com/kernel/member/common/exception/CustomerNotFoundException.java
  member/src/main/java/com/kernel/member/common/exception/ManagerNotFoundException.java
  member/src/main/java/com/kernel/member/common/exception/MemberExceptionHandler.java
  member/src/main/java/com/kernel/member/repository/CustomManagerRepositoryImpl.java
Labels: ⚠️ bug

#252 [Feature] 매니저의 예약 수락 / 거절 기능 추가
  reservation/src/main/java/com/kernel/reservation/common/enums/ReservationErrorCode.java
  reservation/src/main/java/com/kernel/reservation/common/handler/ReservationExceptionHandler.java
  reservation/src/main/java/com/kernel/reservation/controller/ManagerReservationController.java
  reservation/src/main/java/com/kernel/reservation/repository/CustomManagerReservationRepositoryImpl.java
  reservation/src/main/java/com/kernel/reservation/repository/ReservationMatchRepository.java
  reservation/src/main/java/com/kernel/reservation/service/ManagerReservationService.java
  reservation/src/main/java/com/kernel/reservation/service/ManagerReservationServiceImpl.java
  reservation/src/main/java/com/kernel/reservation/service/info/ManagerReservationDetailInfo.java
  reservation/src/main/java/com/kernel/reservation/service/response/ManagerReservationRspDTO.java
  shared-domain/src/main/java/com/kernel/sharedDomain/domain/entity/Reservation.java
Labels: 🔨 feature

#254 [Refactor] 매니저 체크인/체크아웃 기능 리펙토링
  global/src/main/java/com/kernel/global/config/SecurityConfig.java
  global/src/main/java/com/kernel/global/controller/FileUploadController.java
  global/src/main/java/com/kernel/global/domain/entity/File.java
  global/src/main/java/com/kernel/global/service/FileUploadService.java
  global/src/main/java/com/kernel/global/service/FileUploadServiceImpl.java
  global/src/main/java/com/kernel/global/service/dto/response/PresignedUrlRspDTO.java
  reservation/src/main/java/com/kernel/reservation/common/enums/ServiceCheckLogErrorCode.java
  reservation/src/main/java/com/kernel/reservation/common/exception/ServiceCheckLogException.java
  reservation/src/main/java/com/kernel/reservation/common/handler/ServiceCheckLogExceptionHandler.java
  reservation/src/main/java/com/kernel/reservation/controller/ManagerReservationController.java
  reservation/src/main/java/com/kernel/reservation/domain/entity/ServiceCheckLog.java
  reservation/src/main/java/com/kernel/reservation/repository/CustomManagerReservationRepositoryImpl.java
  reservation/src/main/java/com/kernel/reservation/repository/ServiceCheckLogRepository.java
  reservation/src/main/java/com/kernel/reservation/service/ManagerReservationService.java
  reservation/src/main/java/com/kernel/reservation/service/ManagerReservationServiceImpl.java
  reservation/src/main/java/com/kernel/reservation/service/request/ServiceCheckInReqDTO.java
  reservation/src/main/java/com/kernel/reservation/service/request/ServiceCheckOutReqDTO.java
  reservation/src/main/java/com/kernel/reservation/service/response/ServiceCheckInRspDTO.java
  reservation/src/main/java/com/kernel/reservation/service/response/ServiceCheckOutRspDTO.java
  reservation/src/main/java/com/kernel/reservation/service/response/common/ServiceCheckLogErrorRspDTO.java
  shared-domain/src/main/java/com/kernel/sharedDomain/domain/entity/Reservation.java
Labels: 🔧 refactor

#261 [Fix] 매니저 회원가입 오류 수정
  global/src/main/java/com/kernel/global/common/constant/SecurityUrlConstants.java
  member/src/main/java/com/kernel/member/repository/ManagerStatisticRepository.java
  member/src/main/java/com/kernel/member/service/ManagerServiceImpl.java
  member/src/main/java/com/kernel/member/service/request/AvailableTimeReqDTO.java
  member/src/main/java/com/kernel/member/service/request/ManagerReqDTO.java
  member/src/main/java/com/kernel/member/service/request/ManagerSignupReqDTO.java
Labels: ⚠️ bug

#266 [fix] 로그인 무한 요청 문제 수정
  global/src/main/java/com/kernel/global/common/constant/SecurityUrlConstants.java
  global/src/main/java/com/kernel/global/config/SecurityConfig.java
Labels: ⚠️ bug

#276 [Fix] 클라이언트에서 체크인을 여부를 확인할 때 사용하는 ServiceCheckLogId 변수명을 수정
  reservation/src/main/java/com/kernel/reservation/service/response/ServiceCheckInRspDTO.java
  reservation/src/main/java/com/kernel/reservation/service/response/ServiceCheckOutRspDTO.java
Labels: ⚠️ bug

#279 [Refactor]: 매니저 체크인 / 체크아웃 시 필수였던 파일 id를 선택사항으로 수정
  reservation/src/main/java/com/kernel/reservation/domain/entity/ServiceCheckLog.java
  reservation/src/main/java/com/kernel/reservation/service/request/ServiceCheckInReqDTO.java
  reservation/src/main/java/com/kernel/reservation/service/request/ServiceCheckOutReqDTO.java
Labels: 🔧 refactor

#289 [Refactor] 관리자 계정 업데이트 수정 및 오류 수정
  admin/src/main/java/com/kernel/admin/controller/AdminController.java
  admin/src/main/java/com/kernel/admin/repository/CustomAdminRepositoryImpl.java
  admin/src/main/java/com/kernel/admin/service/AdminService.java
  admin/src/main/java/com/kernel/admin/service/AdminServiceImpl.java
  admin/src/main/java/com/kernel/admin/service/dto/request/AdminSearchReqDTO.java
  admin/src/main/java/com/kernel/admin/service/dto/request/AdminUpdateReqDTO.java
  global/src/main/java/com/kernel/global/common/enums/ErrorCode.java
  global/src/main/java/com/kernel/global/domain/entity/User.java
  global/src/main/java/com/kernel/global/domain/info/AdminUserSearchInfo.java
  global/src/main/java/com/kernel/global/service/dto/condition/AdminUserSearchCondition.java
  member/src/main/java/com/kernel/member/domain/entity/CustomerStatistic.java
  member/src/main/java/com/kernel/member/domain/entity/ManagerStatistic.java
Labels: 🔧 refactor

#292 [Refactor] 회원가입 시 널 에러 발생
  Dockerfile
  member/src/main/java/com/kernel/member/domain/entity/CustomerStatistic.java
  member/src/main/java/com/kernel/member/domain/entity/ManagerStatistic.java
Labels: 🔧 refactor

#295 [Refactor] 예약 프로세스 개선
  reservation/src/main/java/com/kernel/reservation/controller/CustomerReservationController.java
  reservation/src/main/java/com/kernel/reservation/repository/CustomCustomerReservationRepositoryImpl.java
  reservation/src/main/java/com/kernel/reservation/repository/common/CustomMatchRepository.java
  reservation/src/main/java/com/kernel/reservation/repository/common/CustomMatchRepositoryImpl.java
  reservation/src/main/java/com/kernel/reservation/service/MatchService.java
  reservation/src/main/java/com/kernel/reservation/service/MatchServiceImpl.java
  reservation/src/main/java/com/kernel/reservation/service/info/CustomerReservationDetailInfo.java
  reservation/src/main/java/com/kernel/reservation/service/info/MatchedManagersInfo.java
  reservation/src/main/java/com/kernel/reservation/service/request/ManagerReqDTO.java
  reservation/src/main/java/com/kernel/reservation/service/response/CustomerReservationConfirmRspDTO.java
  reservation/src/main/java/com/kernel/reservation/service/response/CustomerReservationDetailRspDTO.java
  reservation/src/main/java/com/kernel/reservation/service/response/common/MatchedManagersRspDTO.java
  reservation/src/main/java/com/kernel/reservation/service/response/common/ReservationMatchedRspDTO.java
Labels: 🔧 refactor

#296 [Feature] 소셜로그인 구현
  global/build.gradle
  global/src/main/java/com/kernel/global/common/enums/ErrorCode.java
  global/src/main/java/com/kernel/global/common/enums/SocialProvider.java
  global/src/main/java/com/kernel/global/common/handler/CustomOAuth2FailureHandler.java
  global/src/main/java/com/kernel/global/common/handler/CustomOAuth2SuccessHandler.java
  global/src/main/java/com/kernel/global/config/SecurityConfig.java
  global/src/main/java/com/kernel/global/domain/entity/User.java
  global/src/main/java/com/kernel/global/jwt/JwtFilter.java
  global/src/main/java/com/kernel/global/jwt/JwtTokenProvider.java
  global/src/main/java/com/kernel/global/repository/UserRepository.java
  global/src/main/java/com/kernel/global/security/CustomLoginFilter.java
  global/src/main/java/com/kernel/global/service/CustomOAuth2UserService.java
  global/src/main/java/com/kernel/global/service/CustomOAuth2UserServiceImpl.java
  global/src/main/java/com/kernel/global/service/GoogleOAuth2Service.java
  global/src/main/java/com/kernel/global/service/dto/request/OAuthLoginReqDTO.java
  global/src/main/java/com/kernel/global/service/dto/response/OAuthLoginResult.java
  global/src/main/java/com/kernel/global/service/dto/response/OAuthLoginRspDTO.java
  member/src/main/java/com/kernel/member/common/annotation/ValidUserSignup.java
  member/src/main/java/com/kernel/member/common/validator/ValidUserSignupValidator.java
  member/src/main/java/com/kernel/member/controller/CustomerController.java
  member/src/main/java/com/kernel/member/controller/ManagerController.java
  member/src/main/java/com/kernel/member/domain/entity/Manager.java
  member/src/main/java/com/kernel/member/service/ManagerServiceImpl.java
  member/src/main/java/com/kernel/member/service/common/request/UserSignupReqDTO.java
Labels: 🔨 feature

#298 Fix: 기존 사용자 소셜 로그인시 role을 조회한 사용자의 role을 응답하도록 수정
  global/src/main/java/com/kernel/global/service/CustomOAuth2UserServiceImpl.java
Labels: ⚠️ bug

#301 [Feature] 정산 기능 개발
  payment/src/main/java/com/kernel/settlement/common/enums/SettlementConfig.java
  payment/src/main/java/com/kernel/settlement/common/enums/SettlementStatus.java
  payment/src/main/java/com/kernel/settlement/common/exception/SettlementErrorCode.java
  payment/src/main/java/com/kernel/settlement/common/exception/SettlementException.java
  payment/src/main/java/com/kernel/settlement/common/exception/SettlementExceptionHandler.java
  payment/src/main/java/com/kernel/settlement/common/utils/SettlementCalculator.java
  payment/src/main/java/com/kernel/settlement/controller/AdminSettlementController.java
  payment/src/main/java/com/kernel/settlement/controller/ManagerSettlementController.java
  payment/src/main/java/com/kernel/settlement/domain/Settlement.java
  payment/src/main/java/com/kernel/settlement/repository/AdminSettlementRepository.java
  payment/src/main/java/com/kernel/settlement/repository/CustomAdminSettleRepository.java
  payment/src/main/java/com/kernel/settlement/repository/CustomAdminSettleRepositoryImpl.java
  payment/src/main/java/com/kernel/settlement/repository/CustomManagerSettleRepository.java
  payment/src/main/java/com/kernel/settlement/repository/CustomManagerSettleRepositoryImpl.java
  payment/src/main/java/com/kernel/settlement/repository/ManagerSettlementRepository.java
  payment/src/main/java/com/kernel/settlement/schduler/SettlementScheduler.java
  payment/src/main/java/com/kernel/settlement/service/AdminSettlementService.java
  payment/src/main/java/com/kernel/settlement/service/AdminSettlementServiceImpl.java
  payment/src/main/java/com/kernel/settlement/service/ManagerSettlementService.java
  payment/src/main/java/com/kernel/settlement/service/ManagerSettlementServiceImpl.java
  payment/src/main/java/com/kernel/settlement/service/dto/request/AdminSettlementSearchCond.java
  payment/src/main/java/com/kernel/settlement/service/dto/request/ManagerSettlementSearchCond.java
  payment/src/main/java/com/kernel/settlement/service/dto/request/SettlementCreateReqDTO.java
  payment/src/main/java/com/kernel/settlement/service/dto/response/AdminSettlementSumRspDTO.java
  payment/src/main/java/com/kernel/settlement/service/dto/response/AdminSettlementSummaryRspDTO.java
  payment/src/main/java/com/kernel/settlement/service/dto/response/AdminThisWeekEstimatedRspDto.java
  payment/src/main/java/com/kernel/settlement/service/dto/response/ManagerSettlementSumRspDTO.java
  payment/src/main/java/com/kernel/settlement/service/dto/response/ManagerSettlementSummaryRspDTO.java
  payment/src/main/java/com/kernel/settlement/service/dto/response/ManagerThisWeekEstimatedRspDto.java
  payment/src/main/java/com/kernel/settlement/service/dto/response/SettlementCreateRspDTO.java
  payment/src/main/java/com/kernel/settlement/service/info/AdminSettlementSummaryInfo.java
  payment/src/main/java/com/kernel/settlement/service/info/ManagerSettlementSummaryInfo.java
  payment/src/main/java/com/kernel/settlement/service/info/SettledAmountWithPlatformFeeInfo.java
  reservation/src/main/java/com/kernel/reservation/domain/entity/ReservationCancel.java
  reservation/src/main/java/com/kernel/reservation/port/ReservationQueryPortImpl.java
  reservation/src/main/java/com/kernel/reservation/repository/common/ReservationQueryPortRepository.java
  shared-domain/src/main/java/com/kernel/sharedDomain/service/ReservationQueryPort.java
  shared-domain/src/main/java/com/kernel/sharedDomain/service/response/ReservationManagerMappingInfo.java
  shared-domain/src/main/java/com/kernel/sharedDomain/service/response/ReservationScheduleInfo.java
  src/main/java/com/kernel/ApiApplication.java
Labels: 🔨 feature

#308 refactor : 기존 모듈 삭제
  common/gradle/wrapper/gradle-wrapper.jar
  common/gradle/wrapper/gradle-wrapper.properties
  common/src/main/generated/.gitkeep
  common/src/main/java/com/kernel/common/admin/controller/AdminBannerController.java
  common/src/main/java/com/kernel/common/admin/controller/AdminServiceCategoryController.java
  common/src/main/java/com/kernel/common/admin/dto/mapper/AdminBannerMapper.java
  common/src/main/java/com/kernel/common/admin/dto/mapper/AdminManagerMapper.java
  common/src/main/java/com/kernel/common/admin/dto/mapper/AdminMapper.java
  common/src/main/java/com/kernel/common/admin/dto/mapper/AdminSearchMapper.java
  common/src/main/java/com/kernel/common/admin/dto/mapper/CustomerMapper.java
  common/src/main/java/com/kernel/common/admin/dto/mapper/ServiceCategoryMapper.java
  common/src/main/java/com/kernel/common/admin/dto/request/AdminBannerReqDTO.java
  common/src/main/java/com/kernel/common/admin/dto/request/AdminServiceCategoryReqDTO.java
  common/src/main/java/com/kernel/common/admin/dto/response/AdminBannerRspDTO.java
  common/src/main/java/com/kernel/common/admin/dto/response/AdminServiceCategoryRspDTO.java
  common/src/main/java/com/kernel/common/admin/service/AdminBannerService.java
  common/src/main/java/com/kernel/common/admin/service/AdminBannerServiceImpl.java
  common/src/main/java/com/kernel/common/admin/service/AdminServiceCategoryService.java
  common/src/main/java/com/kernel/common/admin/service/AdminServiceCategoryServiceImpl.java
  common/src/main/java/com/kernel/common/admin/validator/BannerPeriodValidator.java
  common/src/main/java/com/kernel/common/admin/validator/ValidBannerPeriod.java
  common/src/main/java/com/kernel/common/global/AuthenticatedUser.java
  common/src/main/java/com/kernel/common/global/enums/AuthorType.java
  common/src/main/java/com/kernel/common/global/enums/BannerStatus.java
  common/src/main/java/com/kernel/common/global/enums/DayOfWeek.java
  common/src/main/java/com/kernel/common/global/enums/FeedbackType.java
  common/src/main/java/com/kernel/common/global/enums/Gender.java
  common/src/main/java/com/kernel/common/global/enums/PostStatus.java
  common/src/main/java/com/kernel/common/global/enums/ReplyStatus.java
  common/src/main/java/com/kernel/common/global/enums/UserStatus.java
  common/src/main/java/com/kernel/common/global/enums/UserType.java
  common/src/main/java/com/kernel/common/global/security/AdminUserDetails.java
  common/src/main/java/com/kernel/common/global/security/CustomerUserDetails.java
  common/src/main/java/com/kernel/common/global/security/ManagerUserDetails.java
  common/src/main/java/com/kernel/common/manager/controller/ManagerPaymentController.java
  common/src/main/java/com/kernel/common/manager/dto/mapper/CleaningLogMapper.java
  common/src/main/java/com/kernel/common/manager/dto/mapper/ManagerReviewMapper.java
  common/src/main/java/com/kernel/common/manager/dto/request/ManagerSignupReqDTO.java
  common/src/main/java/com/kernel/common/manager/dto/request/ManagerTerminationReqDTO.java
  common/src/main/java/com/kernel/common/manager/dto/request/ManagerUpdateReqDTO.java
  common/src/main/java/com/kernel/common/manager/dto/response/ManagerInfoRspDTO.java
  common/src/main/java/com/kernel/common/manager/dto/response/ManagerPaymentRspDTO.java
  common/src/main/java/com/kernel/common/manager/repository/CustomManagerPaymentRepositoryImpl.java
  common/src/main/java/com/kernel/common/manager/repository/CustomManagerPaymentRepositroy.java
  common/src/main/java/com/kernel/common/manager/repository/CustomManagerRepository.java
  common/src/main/java/com/kernel/common/manager/repository/CustomManagerRepositoryImpl.java
  common/src/main/java/com/kernel/common/manager/repository/ManagerRepository.java
  common/src/main/java/com/kernel/common/manager/service/ManagerPaymentService.java
  common/src/main/java/com/kernel/common/manager/service/ManagerPaymentServiceImpl.java
  common/src/main/java/com/kernel/common/repository/BannerRepository.java
  common/src/test/java/com/kernel/common/service/AdminManagerServiceTest.java
Labels: 🔧 refactor

#309 Readme
  README.md
Labels: 🔨 feature

#311 Update README.md
  README.md
Labels: 🔧 refactor
