Repository Kernel360/KBE5_HALO_BE, pull requests merged in 2025-06, with the labels that each got.

#81 #80: [매니저] 예약 관리 기능 구현
  common/src/main/java/com/kernel/common/global/enums/ReservationStatus.java
  common/src/main/java/com/kernel/common/manager/controller/ManagerInquiryController.java
  common/src/main/java/com/kernel/common/manager/controller/ManagerReservationController.java
  common/src/main/java/com/kernel/common/manager/dto/mapper/CleaningLogMapper.java
  common/src/main/java/com/kernel/common/manager/dto/mapper/ManagerInquiryMapper.java
  common/src/main/java/com/kernel/common/manager/dto/mapper/ManagerReviewMapper.java
  common/src/main/java/com/kernel/common/manager/dto/request/ManagerReservationSearchCondDTO.java
  common/src/main/java/com/kernel/common/manager/dto/response/ManagerInquiryRspDTO.java
  common/src/main/java/com/kernel/common/manager/dto/response/ManagerInquirySummaryRspDTO.java
  common/src/main/java/com/kernel/common/manager/dto/response/ManagerReservationRspDTO.java
  common/src/main/java/com/kernel/common/manager/dto/response/ManagerReservationSummaryRspDTO.java
  common/src/main/java/com/kernel/common/manager/entity/CleaningLog.java
  common/src/main/java/com/kernel/common/manager/repository/CleaningLogRepository.java
  common/src/main/java/com/kernel/common/manager/repository/CustomManagerReservationRepository.java
  common/src/main/java/com/kernel/common/manager/repository/CustomManagerReservationRepositoryImpl.java
  common/src/main/java/com/kernel/common/manager/repository/ManagerReservationRepository.java
  common/src/main/java/com/kernel/common/manager/repository/ManagerReviewRepository.java
  common/src/main/java/com/kernel/common/manager/service/CleaningLogServiceImpl.java
  common/src/main/java/com/kernel/common/manager/service/ManagerInquiryService.java
  common/src/main/java/com/kernel/common/manager/service/ManagerInquiryServiceImpl.java
  common/src/main/java/com/kernel/common/manager/service/ManagerReservationService.java
  common/src/main/java/com/kernel/common/manager/service/ManagerReservationServiceImpl.java
  common/src/main/java/com/kernel/common/manager/service/ManagerReviewServiceImpl.java
  common/src/main/java/com/kernel/common/reservation/entity/Reservation.java
  common/src/main/java/com/kernel/common/reservation/entity/Review.java
  common/src/main/java/com/kernel/common/reservation/repository/.gitkeep
  common/src/main/java/com/kernel/common/reservation/repository/ReservationRepository.java
Labels: Feature

#182 [Refactor] admin 모듈 entity, enum 추가
  admin/src/main/java/com/kernel/admin/domain/entity/Banner.java
  admin/src/main/java/com/kernel/admin/domain/entity/Board.java
  admin/src/main/java/com/kernel/admin/domain/enumerate/BoardType.java
Labels: 🔧 refactor

#183 refactor : Evalutaion 모듈 엔티티 추가
  evaluation/src/main/java/com/kernel/evaluation/domain/.gitkeep
  evaluation/src/main/java/com/kernel/evaluation/domain/entity/Feedback.java
  evaluation/src/main/java/com/kernel/evaluation/domain/entity/Review.java
  evaluation/src/main/java/com/kernel/evaluation/domain/enumerate/FeedbackType.java
Labels: 🔧 refactor

#186 [리펙트] member 모듈 manager 관련 entity, enum 추가
  member/src/main/java/com/kernel/member/domain/entity/AvailableTime.java
  member/src/main/java/com/kernel/member/domain/entity/Manager.java
  member/src/main/java/com/kernel/member/domain/entity/ManagerStatistic.java
  member/src/main/java/com/kernel/member/domain/enumerate/ContractStatus.java
  member/src/main/java/com/kernel/member/exception/.gitkeep
Labels: 🔧 refactor

#188 [refactor] member 모듈 - 매니저 계약 해지 테이블 복원 및 모듈 구조 변경
  member/src/main/java/com/kernel/member/common/enumerate/ContractStatus.java
  member/src/main/java/com/kernel/member/common/enumerate/Gender.java
  member/src/main/java/com/kernel/member/common/exception/.gitkeep
  member/src/main/java/com/kernel/member/domain/entity/Manager.java
  member/src/main/java/com/kernel/member/domain/entity/ManagerTermination.java
  member/src/main/java/com/kernel/member/domain/entity/UserInfo.java
Labels: 🔧 refactor

#189 [refactor] global 모듈과 common 모듈 통합, User entity 추가
  commonNew/src/main/java/com/kernel/common/domain/enumerate/ReceiverType.java
  commonNew/src/main/java/com/kernel/common/repository/.gitkeep
  commonNew/src/main/java/com/kernel/common/service/.gitkeep
  global/src/main/java/com/kernel/global/common/enumerate/PostStatus.java
  global/src/main/java/com/kernel/global/common/enumerate/ReceiverType.java
  global/src/main/java/com/kernel/global/common/enumerate/UserRole.java
  global/src/main/java/com/kernel/global/common/enumerate/UserStatus.java
  global/src/main/java/com/kernel/global/common/exception/.gitkeep
  global/src/main/java/com/kernel/global/domain/entity/File.java
  global/src/main/java/com/kernel/global/domain/entity/Notification.java
  global/src/main/java/com/kernel/global/domain/entity/User.java
  global/src/main/java/com/kernel/global/exception/.gitkeep
Labels: 🔧 refactor

#190 각 모듈별 build.gradle 추가
  .gitignore
  admin/build.gradle
  build.gradle
  evaluation/build.gradle
  global/build.gradle
  global/src/main/java/com/kernel/global/common/properties/AwsProperties.java
  global/src/main/java/com/kernel/global/common/properties/JwtProperties.java
  inquiry/build.gradle
  member/build.gradle
  payment/build.gradle
  reservation/build.gradle
  settings.gradle
  src/main/java/com/kernel/ApiApplication.java
Labels: 🔧 refactor

#195 Create feature_request.md
  .github/PULL_REQUEST_TEMPLATE/feature_request.md
Labels: 🔨 feature

#197 Create refactor.md
  .github/PULL_REQUEST_TEMPLATE/refactor.md
Labels: 🔨 feature

#200 refactor : member 모듈에 수요자 기능 추가
  api/src/main/java/com/kernel/app/controller/CustomerAuthController.java
  api/src/main/java/com/kernel/app/dto/mapper/CustomerAuthMapper.java
  api/src/main/java/com/kernel/app/repository/CustomerAuthRepository.java
  api/src/main/java/com/kernel/app/service/CustomerAuthService.java
  api/src/main/java/com/kernel/app/service/CustomerAuthServiceImpl.java
  common/src/main/java/com/kernel/common/customer/dto/request/CustomerInfoUpdateReqDTO.java
  common/src/main/java/com/kernel/common/customer/dto/request/CustomerSignupReqDTO.java
  common/src/main/java/com/kernel/common/customer/dto/response/CustomerInfoDetailRspDTO.java
  common/src/main/java/com/kernel/common/customer/entity/Customer.java
  global/src/main/java/com/kernel/global/common/constant/SecurityUrlConstants.java
  global/src/main/java/com/kernel/global/common/enums/ErrorCode.java
  global/src/main/java/com/kernel/global/config/SecurityConfig.java
  global/src/main/java/com/kernel/global/domain/entity/User.java
  global/src/main/java/com/kernel/global/jwt/JwtFilter.java
  global/src/main/java/com/kernel/global/security/CustomLoginFilter.java
  member/build.gradle
  member/src/main/java/com/kernel/member/common/enums/ContractStatus.java
  member/src/main/java/com/kernel/member/common/enums/Gender.java
  member/src/main/java/com/kernel/member/common/exception/.gitkeep
  member/src/main/java/com/kernel/member/common/exception/DuplicateUserException.java
  member/src/main/java/com/kernel/member/controller/.gitkeep
  member/src/main/java/com/kernel/member/controller/CustomerController.java
  member/src/main/java/com/kernel/member/controller/UserController.java
  member/src/main/java/com/kernel/member/domain/entity/Customer.java
  member/src/main/java/com/kernel/member/domain/entity/CustomerStatistic.java
  member/src/main/java/com/kernel/member/domain/entity/Manager.java
  member/src/main/java/com/kernel/member/domain/entity/UserInfo.java
  member/src/main/java/com/kernel/member/repository/.gitkeep
  member/src/main/java/com/kernel/member/repository/CustomerRepository.java
  member/src/main/java/com/kernel/member/repository/UserInfoRepository.java
  member/src/main/java/com/kernel/member/repository/UserRepository.java
  member/src/main/java/com/kernel/member/service/.gitkeep
  member/src/main/java/com/kernel/member/service/CustomerService.java
  member/src/main/java/com/kernel/member/service/CustomerServiceImpl.java
  member/src/main/java/com/kernel/member/service/common/UserInfoService.java
  member/src/main/java/com/kernel/member/service/common/UserInfoServiceImpl.java
  member/src/main/java/com/kernel/member/service/common/UserService.java
  member/src/main/java/com/kernel/member/service/common/UserServiceImpl.java
  member/src/main/java/com/kernel/member/service/common/info/UserAccountInfo.java
  member/src/main/java/com/kernel/member/service/common/info/UserDetailInfo.java
  member/src/main/java/com/kernel/member/service/common/request/UserFindAccountReqDTO.java
  member/src/main/java/com/kernel/member/service/common/request/UserInfoSignupReqDTO.java
  member/src/main/java/com/kernel/member/service/common/request/UserInfoUpdateReqDTO.java
  member/src/main/java/com/kernel/member/service/common/request/UserResetPwdReqDTO.java
  member/src/main/java/com/kernel/member/service/common/request/UserSignupReqDTO.java
  member/src/main/java/com/kernel/member/service/common/request/UserUpdateReqDTO.java
  member/src/main/java/com/kernel/member/service/request/CustomerReqDTO.java
  member/src/main/java/com/kernel/member/service/request/CustomerSignupReqDTO.java
  member/src/main/java/com/kernel/member/service/request/CustomerUpdateReqDTO.java
  member/src/main/java/com/kernel/member/service/request/UserInfoSignupReqDTO.java
  member/src/main/java/com/kernel/member/service/request/UserSignupReqDTO.java
  member/src/main/java/com/kernel/member/service/response/CustomerDetailInfo.java
  member/src/main/java/com/kernel/member/service/response/CustomerDetailRspDTO.java
Labels: 🔧 refactor

#202 Refactor/#173
  common/src/main/java/com/kernel/common/payment/entity/.gitkeep
  common/src/main/java/com/kernel/common/reservation/entity/ServiceCategory.java
  payment/build.gradle
  payment/src/main/java/com/kernel/payment/common/enums/PaymentMethod.java
  payment/src/main/java/com/kernel/payment/common/enums/PaymentStatus.java
  payment/src/main/java/com/kernel/payment/domain/.gitkeep
  payment/src/main/java/com/kernel/payment/domain/payment.java
  reservation/build.gradle
  reservation/src/main/java/com/kernel/reservation/domain/entity/Reservation.java
  reservation/src/main/java/com/kernel/reservation/domain/entity/ServiceCategory.java
Labels: 🔧 refactor

#207 [Refactor] admin 조회 기능 리펙토링
  admin/build.gradle
  admin/src/main/java/com/kernel/admin/controller/.gitkeep
  admin/src/main/java/com/kernel/admin/controller/AdminController.java
  admin/src/main/java/com/kernel/admin/domain/.gitkeep
  admin/src/main/java/com/kernel/admin/repository/.gitkeep
  admin/src/main/java/com/kernel/admin/repository/AdminRepository.java
  admin/src/main/java/com/kernel/admin/repository/CustomAdminRepository.java
  admin/src/main/java/com/kernel/admin/repository/CustomAdminRepositoryImpl.java
  admin/src/main/java/com/kernel/admin/service/.gitkeep
  admin/src/main/java/com/kernel/admin/service/AdminService.java
  admin/src/main/java/com/kernel/admin/service/AdminServiceImpl.java
  admin/src/main/java/com/kernel/admin/service/dto/request/AdminSearchReqDTO.java
  admin/src/main/java/com/kernel/admin/service/dto/request/AdminSignupReqDTO.java
  admin/src/main/java/com/kernel/admin/service/dto/request/AdminUpdateReqDTO.java
  admin/src/main/java/com/kernel/admin/service/dto/response/AdminDetailRspDTO.java
  admin/src/main/java/com/kernel/admin/service/dto/response/AdminRspDTO.java
  admin/src/main/java/com/kernel/admin/service/dto/response/AdminSearchRspDTO.java
  global/src/main/java/com/kernel/global/domain/entity/User.java
  global/src/main/java/com/kernel/global/domain/info/AdminUserSearchInfo.java
  global/src/main/java/com/kernel/global/service/dto/condition/AdminUserSearchCondition.java
  member/src/main/java/com/kernel/member/service/common/UserServiceImpl.java
Labels: 🔧 refactor

#218 Create PULL_REQUEST_TEMPLATE.md
  .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md
Labels: 🔨 feature

#220 Rename .github/ISSUE_TEMPLATE/PULL_REQUEST_TEMPLATE.md to .github/PUL…
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 🔨 feature

#221 [Feature] Swagger UI 추가
  admin/build.gradle
  admin/src/main/java/com/kernel/admin/controller/AdminController.java
  api/gradle/wrapper/gradle-wrapper.jar
  api/gradle/wrapper/gradle-wrapper.properties
  api/src/main/java/com/kernel/app/controller/AdminAuthController.java
  api/src/main/java/com/kernel/app/dto/mapper/AdminAuthMapper.java
  api/src/main/java/com/kernel/app/dto/reponse/UserLoginRspDTO.java
  api/src/main/java/com/kernel/app/dto/request/UserLoginReqDTO.java
  api/src/main/java/com/kernel/app/repository/AdminAuthRepository.java
  api/src/main/java/com/kernel/app/service/AdminAuthService.java
  api/src/main/java/com/kernel/app/service/AdminAuthServiceImpl.java
  api/src/test/java/com/kernel/app/ApiApplicationTests.java
  evaluation/build.gradle
  evaluation/src/main/java/com/kernel/evaluation/controller/CustomerFeedbackController.java
  evaluation/src/main/java/com/kernel/evaluation/controller/CustomerReviewController.java
  evaluation/src/main/java/com/kernel/evaluation/controller/ManagerReviewController.java
  global/build.gradle
  global/src/main/java/com/kernel/global/common/constant/SecurityUrlConstants.java
  global/src/main/java/com/kernel/global/config/SwaggerConfig.java
  global/src/main/java/com/kernel/global/config/SwaggerGroupedConfig.java
  global/src/main/java/com/kernel/global/controller/FileUploadController.java
  global/src/main/java/com/kernel/global/controller/ReissueController.java
  inquiry/build.gradle
  inquiry/src/main/java/com/kernel/inquiry/controller/inquiry/InquiryCustomerCommandController.java
  inquiry/src/main/java/com/kernel/inquiry/controller/inquiry/InquiryCustomerQueryController.java
  inquiry/src/main/java/com/kernel/inquiry/controller/inquiry/InquiryManagerCommandController.java
  inquiry/src/main/java/com/kernel/inquiry/controller/inquiry/InquiryManagerQueryController.java
  inquiry/src/main/java/com/kernel/inquiry/controller/reply/ReplyController.java
  member/build.gradle
  member/src/main/java/com/kernel/member/controller/CustomerController.java
  member/src/main/java/com/kernel/member/controller/ManagerController.java
  member/src/main/java/com/kernel/member/controller/UserController.java
  payment/build.gradle
  reservation/build.gradle
  reservation/src/main/java/com/kernel/reservation/controller/ManagerReservationController.java
Labels: 🔨 feature

#223 Create refactor_issue.md
  .github/ISSUE_TEMPLATE/refactor_issue.md
Labels: 🔨 feature

#224 Create feature_issue.md
  .github/ISSUE_TEMPLATE/feature_issue.md
Labels: 🔨 feature
